baseURL: "https://forrestfwilliams.com"
locale: "en-us"
title: "Forrest Williams"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

enableRobotsTXT: true
# disqusShortname: forrestfwilliams
# googleAnalytics: G-FRMGYFYWXT

markup:
  goldmark:
    renderer:
      unsafe: true

relativeURLs: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

params:
  title: ""
  description: Forrest Williams
  # staticPath: ""  # The path to serve the static files from
  favicon: "/satellite-dish-solid.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/satellite-dish-solid.svg" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    # brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    # menus:
    #   disableAbout: false
    #   disableExperience: false
    #   disableEducation: false
    #   disableProjects: false
    #   disableAchievements: false
    #   disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Forrest"
    subtitle: "I use SAR satellites to monitor the Earth"
    content: ""
    image: /index/me_bw.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/forrestwilliams_resume.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/forrestfwilliams
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/forrest-williams-geospatial/

  # About
  about:
    enable: true
    title: "About Me"
    image: /index/me_bw.jpg
    content: |-
      I am a Senior Radar Systems Engineer with a passion for expanding what we can do with SAR. I have a PhD in geology and radar remote sensing and am an accomplished software engineer.

      I currently work at [Ursa Space Systems](https://ursaspace.com), where I lead a commercial airborne moving target identification (AMTI) project.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Radar signal processing"
        - "MTI"
        - "Edge computing"
        - "Python & C++"

  experience:
    enable: true
    # title: "Custom Name"
    items:
      - company: "Ursa"
        companyUrl: "https://ursaspace.com"
        jobs:
          - name: "Senior Radar Systems Engineer"
            date: "Nov 2025 - Present"
            content: "At Ursa I lead a commercial airborne moving target identification (AMTI) project and serve as one of Ursa's primary radar experts. This includes:
              \n- Leading a commercial airborne moving target identification (AMTI) project
              \n- Developing cutting-edge SAR signal processing algorithms
              \n- Developing a Claude Skill for SAR intelligence
              "
      - company: "ASF"
        companyUrl: "https://asf.alaska.edu/about-asf/"
        jobs:
          - name: "Senior Research Software Engineer"
            date: "Apr 2022 - Oct 2025"
            content: "At the Alaska Satellite Facility I worked within a dedicated software engineering team to design new SAR products and services. This work included:
              \n- Developed [MultiRTC](https://github.com/forrestfwilliams/multirtc), a Python pacakge for mulit-mission RTC processing
              \n- Lead the development of [ASF's Displacement Portal](https://displacement.asf.alaska.edu)
              \n- Lead the development of ASF's Sentinel-1 burst offerings
              \n- Participating in NASA Disaster's disaster response activities
              \n- Lead tutorials and workshops on SAR data usage for the NASA community
              "
      - company: "JPL"
        companyUrl: "https://www.jpl.nasa.gov"
        jobs:
          - name: "Signal Processing Intern"
            date: "May 2019 - April 2022"
            content: "While I was a graduate student, I interned with at the Jet Propulsion Laboratory (JPL). This work included:
              \n- Used open-source InSAR tools and UAVSAR data to track fault and landslide movement across California
              \n- Developed UAVSAR time-series processing workflows that were used as the basis for NISAR validation product creation
              \n- Explored multi-stage InSAR unwrapping algorithms using SNAPHU
              "
      - company: "ISU"
        companyUrl: "https://www.iastate.edu"
        jobs:
          - name: "Remote Sensing Data Scientist"
            date: "May 2019 - April 2022"
            content: "While pursuing my PhD, I worked part-time as a remote sensing data scientist at Iowa State University. This work included:
              \n- Built a machine learning model to facilitate the prediction of U.S. crop residue cover measurement
              \n- Designed image processing workflows within Google Earth Engine
              "

  # Education
  education:
    enable: true
    # title: "Custom Name"
    # index: true
    items:
      - title: "Doctor of Philosophy in Geoscience"
        school:
          name: "Massey University, New Zealand"
          url: "https://www.massey.ac.nz"
        date: "2019 - 2022"
        content: |-
          - Used Python’s geospatial libraries and Sentinel-1 SAR data to monitor natural hazards
          - Utilized machine learning models to analyze patterns in landslide occurrence
          - Contributor to open-source SAR data analysis platforms (ISCE2 and MintPy)
      - title: "Masters of Science in Environmental Science"
        school:
          name: "Iowa State University"
          url: "https://www.iastate.edu"
        date: "2017 - 2019"
        content: |-
          - Built and tested an ESRI Python toolbox for surface water detection and river monitoring
          - Managed a multi-year field research project
          - Presented at four conferences and won two student research presentation competitions
          - Recieved a Graduate Certificate in GIS
      - title: "Bachelors of Art in Geology"
        school:
          name: "Carleton College"
          url: "https://www.carleton.edu"
        date: "2012 - 2016"
        content: |-
          - Participated in two geology field camps in Italy and New Zealand
          - Recieved an award for outstanding undergraduate research
          - Co-founder of Carleton's running club

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    title: "Open-Source Projects"
    items:
      - title: MultiRTC
        content: I'm the creator and lead developer of MultiRTC. A python library for creating ISCE3-based RTCs for all modern SAR missions (eventually).
        image: /multirtc_badge.png
        featured:
          name: Code
          link: https://github.com/multisar/multirtc 
        badges:
          - "SAR"
          - "Multi-Mission"
          - "Terrain Correction"
        links:
          - icon: fab fa-github
            url: https://github.com/multisar/multirtc

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: forrestfwilliams@icloud.com
    btnName: E-Mail me

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/forrestfwilliams
      linkedin: https://www.linkedin.com/in/forrest-williams-geospatial/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
